# Generated by Django 2.2.6 on 2023-03-11 19:41

from django.conf import settings
from django.db import migrations
from exchange.utils import calc_new_market_price


def create_symbols(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Symbol = apps.get_model('exchange', 'Symbol')
    Symbol.objects.using(db_alias).create(
        ticker='h&h',
        description='ПАО "Рога и Копыта"',
    )


def create_initial_tick(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Symbol = apps.get_model('exchange', 'Symbol')
    symbol = Symbol.objects.using(db_alias).get(ticker='h&h')

    Tick = apps.get_model('exchange', 'Tick')
    tick = Tick.objects.using(db_alias).create(
        symbol=symbol,
        price=settings.START_PRICE,
    )
    for i in range(99):
        Tick.objects.using(db_alias).create(
            symbol=symbol,
            price=calc_new_market_price(tick.price),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_symbols),
        migrations.RunPython(create_initial_tick),
    ]
