# Generated by Django 2.2.6 on 2023-03-11 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения сделки')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.Operation', verbose_name='Операция')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Symbol', verbose_name='Инструмент')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ('-created',),
            },
        ),
    ]
