# Generated by Django 2.2.6 on 2023-03-10 13:09

from django.db import migrations


def create_operations(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Operation = apps.get_model('terminal', 'Operation')
    Operation.objects.using(db_alias).create(name='buy')
    Operation.objects.using(db_alias).create(name='sell')


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_operations),
    ]
